@hostname = 0.0.0.0
@port = 3000
@host = http://{{hostname}}:{{port}}
@collection = users

### Create a new user
POST {{host}}/{{collection}}
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

### Get all users
GET {{host}}/{{collection}}

### Get a single user
# @userId is set from the response of the "Create a new user" request
GET {{host}}/{{collection}}/{{userId}}

### Update a user
PUT {{host}}/{{collection}}/{{userId}}
Content-Type: application/json

{
  "email": "john.doe.updated@example.com"
}

### Delete a user
DELETE {{host}}/{{collection}}/{{userId}}

### Create a new collection
POST {{host}}/create2929/products

### Get all collections
GET {{host}}/2929collection

### Upload a file
POST {{host}}/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="referenceId"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.txt"
Content-Type: text/plain

Hello, world!
------WebKitFormBoundary7MA4YWxkTrZu0gW--
